### ISSUE TITLE
Shape mismatch in velocity.compute_speed

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_validation#160]
Running `validate_features.py`, I get the following error:

```
Calculating Morphology Features
Calculating Locomotion Features
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 680, in runfile
    execfile(filename, namespace)
  File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 85, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "C:/Users/mcurrie/Desktop/GitHub/movement_validation/tests/validate_features.py", line 66, in <module>
    test_features()
  File "C:/Users/mcurrie/Desktop/GitHub/movement_validation/tests/validate_features.py", line 38, in test_features
    openworm_features = mv.WormFeatures(nw)
  File "..\movement_validation\features\worm_features.py", line 655, in __init__
    self.locomotion = WormLocomotion(self)
  File "..\movement_validation\features\worm_features.py", line 179, in __init__
    self.velocity = locomotion_features.LocomotionVelocity(features_ref)
  File "..\movement_validation\features\locomotion_features.py", line 139, in __init__
    ventral_mode)[0:2]
  File "..\movement_validation\features\velocity.py", line 489, in compute_speed
    speed[keep_mask] = distance / time
ValueError: shape mismatch: value array of shape (4073,) could not be broadcast to indexing result of shape (4073,4642)
```

**Comment by MichaelCurrie** [comment]
This is happening because for some reason @JimHokanson you are now declaring
```
speed = np.full((1, num_frames),np.nan)
```
instead of
```
speed = np.empty((num_frames))
```
So `speed.shape = (1,num_frames)` instead of `(num_frames,)`.

So a few lines needed to be modified:

`speed[keep_mask] = distance / time` to `speed[0,keep_mask] = distance / time`, etc.

The old code returned the shape `(1,num_frames)` in the coner case that `frames_per_sample > num_frames`, so perhaps this change is good.

**Comment by JimHokanson** [comment]
Oops. I had meant to test the change and then I got distracted with parenting duties. I think I'd rather that the code was the way it was originally, rather than how you fixed it (i.e. just use (num_frames) on the full() operator rather than (1,num_frames)). Stupid shape mismatch things like this can be a pain in the butt down the road. 

The change was originally made because in the corner case there was a missing return (motion_direction was not being returned). Then to cut down on code size I just initialized everything at the beginning, rather than having initialization statements in the early return case AND in the following (non-early return) case. I also changed the code to use full() instead of the 2 line initialization with empty. This means people would need to use Numpy > 1.8 but I think that is a reasonable request since that version is over a year old.

@MichaelCurrie If you can fix this that would be great, otherwise
