### ISSUE TITLE
Error running validate_features.py: event_data different shape

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_validation#161]
Running `validate_features.py` I have the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 680, in runfile
    execfile(filename, namespace)
  File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 85, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "C:/Users/mcurrie/Desktop/GitHub/movement_validation/tests/validate_features.py", line 66, in <module>
    test_features()
  File "C:/Users/mcurrie/Desktop/GitHub/movement_validation/tests/validate_features.py", line 38, in test_features
    openworm_features = mv.WormFeatures(nw)
  File "..\movement_validation\features\worm_features.py", line 655, in __init__
    self.locomotion = WormLocomotion(self)
  File "..\movement_validation\features\worm_features.py", line 184, in __init__
    nw.length)
  File "..\movement_validation\features\locomotion_features.py", line 325, in __init__
    event_list = ef.get_events(midbody_speed, distance_per_frame)
  File "..\movement_validation\features\events.py", line 141, in get_events
    event_candidates = self.get_start_stop_indices(speed_data, speed_mask)
  File "..\movement_validation\features\events.py", line 268, in get_start_stop_indices
    assert(len(np.shape(event_data)) == 1)
AssertionError
```

Also I'm not sure why this and issue #160 weren't caught by the Travis CI system.  That's worth looking into as well.

**Comment by MichaelCurrie** [comment]
Basically I handled this with:

```
        # Go from shape == (1, 4642) to (4642,) (where 4642 is the number of 
        # frames, for instance)
        event_data = event_data.flatten()
        event_mask = event_mask.flatten()
```

**Comment by JimHokanson** [comment]
@MichaelCurrie In general I'd like to void this kind of code. This code is not at the entrance of the file but in the middle of it. Instead, I'd prefer if we 1) make sure any new code uses a 1d vector when the data only has 1 dimension (that was an error on my part) and 2) Any code being loaded from disk from old files should be corrected at that point. I've gotten bitten by this problem before and you really don't want these statements sprinkled throughout your code. Thanks and my apologies on the initial mistake that caused all of this confusion.
