### ISSUE TITLE
Locomotion shape mismatch issues

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_validation#163]
When running `validate_features.py`:

```
Calculating Morphology Features
Calculating Locomotion Features
Calculating Posture Features
Calculating Path Features

Comparison of computed features to those computed with old Matlab code:
Shape mismatch (4642,) vs (1, 4642): locomotion.velocity.head_tip.speed
Values not equal: locomotion.motion_events.forward.num_video_frames
Event mismatch locomotion.motion_events.backward
Shape mismatch (4642,) vs (1,): locomotion.motion_mode
Mismatch of NaN values per frame is too high: locomotion.bends.head.amplitude
Mismatch in locomotion.crawling_bends events
Values not equal: locomotion.turns.upsilons.num_video_frames
Mismatch in locomotion.turns events
Locomotion: False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 680, in runfile
    execfile(filename, namespace)
  File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 85, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "C:/Users/mcurrie/Desktop/GitHub/movement_validation/tests/validate_features.py", line 66, in <module>
    test_features()
  File "C:/Users/mcurrie/Desktop/GitHub/movement_validation/tests/validate_features.py", line 59, in test_features
    assert(is_test_passed)
AssertionError
```

**Comment by MichaelCurrie** [comment]
OK latest commit fixed some of it, but still these errors remain:

```
Calculating Morphology Features
Calculating Locomotion Features
Calculating Posture Features
Calculating Path Features

Comparison of computed features to those computed with old Matlab code:
Mismatch of NaN values per frame is too high: locomotion.bends.head.amplitude
Mismatch in locomotion.crawling_bends events
Locomotion: False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 680, in runfile
    execfile(filename, namespace)
  File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 85, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "C:/Users/mcurrie/Desktop/GitHub/movement_validation/tests/validate_features.py", line 66, in <module>
    test_features()
  File "C:/Users/mcurrie/Desktop/GitHub/movement_validation/tests/validate_features.py", line 59, in test_features
    assert(is_test_passed)
AssertionError
```

**Comment by JimHokanson** [comment]
This is the old code and has more to do with actually making comparisons properly rather than anything to do with shape changes. This code works with the new feature organization.

In other words, the real issue here is that validate_features.py needs to be written from test_new_feature_organization.py and the old features need to be removed.

**Comment by MichaelCurrie** [comment]
So `validate_features.py` is deprecated?  I should ignore those final Mismatch of NaN values per frame in `locomotion.bends.head.amplitude` and `locomotion.crawling_bends`?

If so we can just close this issue

**Comment by JimHokanson** [comment]
That is correct.
